name: Send DM

on:
  schedule:
    - cron: '0 */4 * * *'   # Har 4 soatda ishga tushadi
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        env:
          X_COOKIES_JSON: ${{ secrets.X_COOKIES_JSON }}
        run: python send_dm.py
